// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraping.proto

package scraping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetScrapingRequest struct {
	TargetLink           string   `protobuf:"bytes,1,opt,name=targetLink,proto3" json:"targetLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetScrapingRequest) Reset()         { *m = GetScrapingRequest{} }
func (m *GetScrapingRequest) String() string { return proto.CompactTextString(m) }
func (*GetScrapingRequest) ProtoMessage()    {}
func (*GetScrapingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e152db9d7e857a1a, []int{0}
}

func (m *GetScrapingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScrapingRequest.Unmarshal(m, b)
}
func (m *GetScrapingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScrapingRequest.Marshal(b, m, deterministic)
}
func (m *GetScrapingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScrapingRequest.Merge(m, src)
}
func (m *GetScrapingRequest) XXX_Size() int {
	return xxx_messageInfo_GetScrapingRequest.Size(m)
}
func (m *GetScrapingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScrapingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScrapingRequest proto.InternalMessageInfo

func (m *GetScrapingRequest) GetTargetLink() string {
	if m != nil {
		return m.TargetLink
	}
	return ""
}

type ScrapingResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Tell                 string   `protobuf:"bytes,3,opt,name=tell,proto3" json:"tell,omitempty"`
	OpeningHours         string   `protobuf:"bytes,4,opt,name=openingHours,proto3" json:"openingHours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScrapingResponse) Reset()         { *m = ScrapingResponse{} }
func (m *ScrapingResponse) String() string { return proto.CompactTextString(m) }
func (*ScrapingResponse) ProtoMessage()    {}
func (*ScrapingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e152db9d7e857a1a, []int{1}
}

func (m *ScrapingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrapingResponse.Unmarshal(m, b)
}
func (m *ScrapingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrapingResponse.Marshal(b, m, deterministic)
}
func (m *ScrapingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrapingResponse.Merge(m, src)
}
func (m *ScrapingResponse) XXX_Size() int {
	return xxx_messageInfo_ScrapingResponse.Size(m)
}
func (m *ScrapingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrapingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScrapingResponse proto.InternalMessageInfo

func (m *ScrapingResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScrapingResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ScrapingResponse) GetTell() string {
	if m != nil {
		return m.Tell
	}
	return ""
}

func (m *ScrapingResponse) GetOpeningHours() string {
	if m != nil {
		return m.OpeningHours
	}
	return ""
}

func init() {
	proto.RegisterType((*GetScrapingRequest)(nil), "GetScrapingRequest")
	proto.RegisterType((*ScrapingResponse)(nil), "ScrapingResponse")
}

func init() { proto.RegisterFile("scraping.proto", fileDescriptor_e152db9d7e857a1a) }

var fileDescriptor_e152db9d7e857a1a = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2e, 0x4a,
	0x2c, 0xc8, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe1, 0x12, 0x72, 0x4f,
	0x2d, 0x09, 0x86, 0x0a, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0x95,
	0x24, 0x16, 0xa5, 0xa7, 0x96, 0xf8, 0x64, 0xe6, 0x65, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x21, 0x89, 0x28, 0x55, 0x70, 0x09, 0x20, 0xb4, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09,
	0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x42, 0x55, 0x83, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0x89, 0x29,
	0x29, 0x45, 0xa9, 0xc5, 0xc5, 0x12, 0x4c, 0x60, 0x61, 0x18, 0x17, 0xa4, 0xba, 0x24, 0x35, 0x27,
	0x47, 0x82, 0x19, 0xa2, 0x1a, 0xc4, 0x16, 0x52, 0xe2, 0xe2, 0xc9, 0x2f, 0x48, 0xcd, 0xcb, 0xcc,
	0x4b, 0xf7, 0xc8, 0x2f, 0x2d, 0x2a, 0x96, 0x60, 0x01, 0xcb, 0xa1, 0x88, 0x19, 0x39, 0x73, 0x71,
	0xc0, 0x6c, 0x16, 0x32, 0xe7, 0xe2, 0x06, 0xb9, 0x3d, 0x23, 0xbf, 0xc0, 0x33, 0x2f, 0x2d, 0x5f,
	0x48, 0x58, 0x0f, 0xd3, 0x27, 0x52, 0x82, 0x7a, 0xe8, 0x0e, 0x55, 0x62, 0x48, 0x62, 0x03, 0xfb,
	0xdd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xdf, 0xac, 0xc7, 0x0d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ScrapingClient is the client API for Scraping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScrapingClient interface {
	GetShopInfo(ctx context.Context, in *GetScrapingRequest, opts ...grpc.CallOption) (*ScrapingResponse, error)
}

type scrapingClient struct {
	cc grpc.ClientConnInterface
}

func NewScrapingClient(cc grpc.ClientConnInterface) ScrapingClient {
	return &scrapingClient{cc}
}

func (c *scrapingClient) GetShopInfo(ctx context.Context, in *GetScrapingRequest, opts ...grpc.CallOption) (*ScrapingResponse, error) {
	out := new(ScrapingResponse)
	err := c.cc.Invoke(ctx, "/Scraping/GetShopInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScrapingServer is the server API for Scraping service.
type ScrapingServer interface {
	GetShopInfo(context.Context, *GetScrapingRequest) (*ScrapingResponse, error)
}

// UnimplementedScrapingServer can be embedded to have forward compatible implementations.
type UnimplementedScrapingServer struct {
}

func (*UnimplementedScrapingServer) GetShopInfo(ctx context.Context, req *GetScrapingRequest) (*ScrapingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShopInfo not implemented")
}

func RegisterScrapingServer(s *grpc.Server, srv ScrapingServer) {
	s.RegisterService(&_Scraping_serviceDesc, srv)
}

func _Scraping_GetShopInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScrapingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScrapingServer).GetShopInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Scraping/GetShopInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScrapingServer).GetShopInfo(ctx, req.(*GetScrapingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scraping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Scraping",
	HandlerType: (*ScrapingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShopInfo",
			Handler:    _Scraping_GetShopInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraping.proto",
}
