version: '2'
services:
  backendapi:
    build:
      ./api/
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./api:/go/src/work
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 5432
      DB_NAME: fullstack_dev_db
  
  tabelogparser:
    build:
      ./backend/scraping/tabelog/
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./backend/scraping/tabelog/:/go/src/work

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: root
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
