version: '2'
services:
  backend:
    build:
      ./api/
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./api:/go/src/work
  bff:
    build:
      ./bff/
    tty: true
    ports:
      - "3030:3030"
    volumes:
      - ./bff:/node/src/work
