version: '2'
services:
  backend:
    build:
      ./api/
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./api:/go/src/work
      
  # bff:
  #   build:
  #     ./bff/
  #   tty: true
  #   ports:
  #     - "3030:3030"
  #   volumes:
  #     - ./bff:/bff/src/work/
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - API_SERVER_PORT=3030

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: root
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
